version: '3.2'

services:
    app:
        build:
            context: .
            dockerfile: ./devops/docker/app/Dockerfile
            args:
                USER_ID: ${USER_ID:-0}
                GROUP_ID: ${GROUP_ID:-0}
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www
